/**
 * ALL user-facing copy lives here. Components import `content` instead of
 * hardcoding text, so wording can be changed (or translated later) in one place.
 * As pages are added, add their sections below.
 */
export const content = {
  site: {
    name: "Car Rental Co.",
    tagline: "Placeholder tagline goes here",
    description:
      "Placeholder description: rent a car in the Philippines with simple online booking.",
    contactPhone: "+63 917 000 0000",
    contactEmail: "hello@example.com",
  },

  seo: {
    titleTemplate: "%s | Car Rental Co.",
    defaultTitle: "Car Rental Co. | Rent a car in the Philippines",
    locale: "en_PH",
  },

  nav: {
    public: [
      { label: "Home", href: "/" },
      { label: "Vehicles", href: "/vehicles" },
      { label: "Special Offers", href: "/special-offers" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    bookCta: { label: "Book now", href: "/book/dates" },
    primaryLabel: "Main navigation",
    skipToContent: "Skip to main content",
  },

  socials: [
    { label: "Facebook", href: "https://facebook.com" },
    { label: "Instagram", href: "https://instagram.com" },
    { label: "TikTok", href: "https://tiktok.com" },
  ],

  footer: {
    columns: [
      {
        title: "Explore",
        links: [
          { label: "Vehicles", href: "/vehicles" },
          { label: "Special offers", href: "/special-offers" },
          { label: "Book now", href: "/book/dates" },
          { label: "About us", href: "/about" },
        ],
      },
      {
        title: "Support",
        links: [
          { label: "Contact us", href: "/contact" },
          { label: "Leave a review", href: "/review" },
          { label: "Staff login", href: "/admin/login" },
        ],
      },
    ],
    phoneLabel: "Call us",
    socialsTitle: "Follow us",
    legal: "© 2026 Car Rental Co. All rights reserved.",
  },

  /** Built-in labels used inside UI kit components (mostly accessibility text). */
  ui: {
    loading: "Loading…",
    close: "Close",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    previousMonth: "Go to previous month",
    nextMonth: "Go to next month",
    selectDate: "Select date",
    selectTime: "Select time",
    dismiss: "Dismiss",
    required: "required",
    opensInNewTab: "opens in a new tab",
    notifications: "Notifications",
    pagination: {
      label: "Pagination",
      previous: "Previous",
      next: "Next",
      page: "Page",
    },
    stepper: { label: "Progress", step: "Step", of: "of", complete: "completed" },
    theme: { toggleToLight: "Switch to light mode", toggleToDark: "Switch to dark mode" },
    sort: { ascending: "sorted ascending", descending: "sorted descending" },
    rating: { stars: (n: number) => `${n} out of 5 stars`, option: (n: number) => `${n} ${n === 1 ? "star" : "stars"}` },
    alert: {
      info: "Note",
      success: "Success",
      warning: "Warning",
      danger: "Error",
    },
  },

  /** Wording for the reusable empty / error / loading states. */
  states: {
    emptyTitle: "Nothing here yet",
    emptyDescription: "There is nothing to show right now.",
    errorTitle: "Something went wrong",
    errorDescription: "We could not load this. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundDescription: "The page you are looking for does not exist or has moved.",
    backHome: "Back to home",
  },

  /** Form error messages. Used by every Zod schema. */
  validation: {
    required: "This field is required.",
    email: "Enter a valid email address.",
    phone: "Enter a valid mobile number, e.g. 0917 123 4567.",
    messageTooShort: "Please write at least 10 characters.",
    dateInPast: "Choose today or a future date.",
    returnBeforePickup: "Return must be after pick-up.",
    consent: "Please tick this box to continue.",
    rating: "Choose a star rating from 1 to 5.",
    license: "Enter your driver's license number.",
  },

  /** The words shown for each id in /src/lib/constants.ts. */
  enums: {
    vehicleCategory: {
      sedan: "Sedan",
      suv: "SUV",
      van: "Van",
      "125cc": "125cc",
      "155cc": "155cc",
    },
    vehicleStatus: { available: "Available", maintenance: "In maintenance", inactive: "Inactive" },
    leadStage: { new: "New", contacted: "Contacted", qualified: "Qualified", won: "Won", lost: "Lost" },
    leadSource: {
      website: "Website",
      phone: "Phone",
      walk_in: "Walk-in",
      facebook: "Facebook",
      referral: "Referral",
    },
    activityType: { note: "Note", call: "Call", status_change: "Status change" },
    bookingStatus: {
      pending: "Pending",
      confirmed: "Confirmed",
      active: "Active",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    paymentMethod: {
      card: "Credit or debit card",
      gcash: "GCash",
      maya: "Maya",
      paypal: "PayPal",
      wise: "Wise",
      pay_at_pickup: "Pay at pick-up",
    },
    paymentStatus: { pending: "Pending", processing: "Processing", paid: "Paid", failed: "Failed" },
  },

  quickSearch: {
    title: "Find your car",
    pickupLocation: "Pick-up location",
    locationPlaceholder: "Paste a Google Maps link, or type an address",
    locationHint: "For example a hotel, airport terminal or barangay.",
    pickupDate: "Pick-up date",
    pickupTime: "Pick-up time",
    returnDate: "Return date",
    returnTime: "Return time",
    submit: "Search vehicles",
  },

  home: {
    meta: {
      description:
        "Placeholder description: browse our cars, pick your dates and book online in minutes. Prices in PHP.",
    },
    hero: {
      title: "Rent a car in the Philippines",
      subtitle: "Placeholder: simple online booking with clear daily prices in PHP.",
    },
    featured: {
      title: "Featured vehicles",
      description: "A few of our most popular cars.",
      viewAll: "View all vehicles",
    },
    howItWorks: {
      title: "How it works",
      steps: [
        { title: "Choose dates and place", body: "Tell us when and where you need the car." },
        { title: "Pick your vehicle", body: "Compare the cars available for your dates." },
        { title: "Book and pay", body: "Confirm your details and pay online or at pick-up." },
        { title: "Pick up and go", body: "Show your booking reference and drive away." },
      ],
    },
    reviews: {
      title: "What customers say",
      description: "Reviews from people who have rented with us.",
      emptyTitle: "No reviews to show yet",
      emptyDescription: "Be the first to tell us how we did.",
      errorTitle: "We could not load the reviews",
    },
    cta: {
      title: "Ready to hit the road?",
      description: "Pick your dates and book in a few minutes.",
      button: "Book now",
    },
  },

  reviews: {
    meta: {
      title: "Leave a review",
      description: "Tell us how we did. Your review goes to our team first.",
    },
    title: "Leave a review",
    subtitle: "Tell us about your experience with our service overall.",
    form: {
      title: "Your review",
      name: "Your name",
      rating: "Your rating",
      comment: "Your comments",
      commentHint: "A few sentences is plenty.",
      reference: "Booking reference",
      referenceHint: "The code from your booking confirmation, like RC-K7M2QA.",
      unknownReference: "We could not find a booking with that reference. Check it and try again.",
      privacyNote: "Reviews are private. Our team reads each one and chooses which to show on the website.",
      submit: "Send review",
      sending: "Sending",
      successTitle: "Thank you for your review",
      successBody: "We received it. Our team will read it and may show it on the website.",
      another: "Write another review",
      errorTitle: "We could not send your review",
      errorBody: "Something went wrong on our side. Please try again.",
    },
  },

  about: {
    meta: {
      title: "About us",
      description: "Placeholder description: learn about our company, our values and our team.",
    },
    title: "About us",
    subtitle: "Placeholder: a short line about the company.",
    story: {
      title: "Our story",
      body: [
        "Placeholder: tell the story of the company here. Who started it, when, and why.",
        "Placeholder: a second paragraph about the fleet, the service and what makes customers come back.",
      ],
    },
    values: {
      title: "What we stand for",
      items: [
        { title: "Reliable vehicles", body: "Placeholder: how the fleet is maintained and checked." },
        { title: "Clear pricing", body: "Placeholder: daily rates in PHP with no surprises." },
        { title: "Friendly service", body: "Placeholder: how the team looks after customers." },
      ],
    },
    team: {
      title: "Meet the team",
      members: [
        { name: "Team member", role: "Role" },
        { name: "Team member", role: "Role" },
        { name: "Team member", role: "Role" },
      ],
    },
    cta: { title: "Questions before you book?", button: "Contact us" },
  },

  specialOffers: {
    meta: {
      title: "Special offers",
      description: "Placeholder description: weekly and monthly rates, a driver, tours and point-to-point trips.",
    },
    title: "Special offers",
    subtitle: "Placeholder: ways to save, or to get more out of your rental.",
    offers: [
      {
        title: "Weekly and monthly rates",
        body: "Placeholder: book by the week or the month for a lower daily rate than a short rental.",
      },
      {
        title: "With a driver",
        body: "Placeholder: add a licensed driver to your booking for an extra charge, and let us do the driving.",
      },
      {
        title: "Tours package",
        body: "Placeholder: a vehicle, a driver and a planned route for day trips and sightseeing.",
      },
      {
        title: "Point-to-point pick-up and drop-off",
        body: "Placeholder: start in one city or province and end in another, instead of returning to where you started.",
      },
    ],
    cta: { title: "Ask about any of these", button: "Contact us" },
  },

  vehicles: {
    meta: {
      title: "Our vehicles",
      description:
        "Placeholder description: compare sedans, SUVs, vans and motorcycles with clear daily rates in PHP.",
    },
    title: "Our vehicles",
    description: "Filter by type, price and seats. Share the page to share your search.",
    filtersTitle: "Filters",
    showFilters: "Show filters",
    hideFilters: "Hide filters",
    filters: {
      category: "Category",
      minSeats: "Seats",
      minPrice: "Min price per day",
      maxPrice: "Max price per day",
      any: "Any",
      noMinimum: "No minimum",
      noMaximum: "No maximum",
      seatsOrMore: (n: number) => `${n}+ seats`,
    },
    sortLabel: "Sort by",
    sorts: {
      "price-asc": "Price: low to high",
      "price-desc": "Price: high to low",
      "name-asc": "Name: A to Z",
      "seats-desc": "Seats: most first",
    },
    resultCount: (n: number) => `${n} ${n === 1 ? "vehicle" : "vehicles"} found`,
    clearFilters: "Clear filters",
    emptyTitle: "No vehicles match your filters",
    emptyDescription: "Try removing a filter or choosing a different price range.",
    trip: {
      title: "Your trip",
      pickup: "Pick-up",
      return: "Return",
      change: "Change search",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
    },
    resultsLabel: "Vehicle results",
  },

  vehicleCard: {
    perDay: "per day",
    totalFor: (days: number) => `Total for ${days} ${days === 1 ? "day" : "days"}`,
    viewDetails: "View details",
    bookNow: "Book now",
    seats: (n: number) => `${n} seats`,
    unavailable: "Unavailable",
  },

  vehicleDetail: {
    back: "All vehicles",
    perDay: "per day",
    specsTitle: "Specifications",
    specs: {
      category: "Category",
      seats: "Seats",
    },
    availabilityTitle: "Availability",
    availableNow: "Available to book",
    unavailableNow: "Not available right now",
    bookNow: "Book now",
    askAbout: "Ask about this vehicle",
    galleryLabel: "Vehicle photos",
    viewPhoto: (n: number) => `View photo ${n}`,
    metaFallbackTitle: "Vehicle",
    metaDescription: (name: string, rate: string) =>
      `Rent the ${name} for ${rate} per day. Book online with clear pricing.`,
  },

  booking: {
    meta: {
      title: "Book your car",
      description: "Book your rental car online in a few simple steps.",
    },
    steps: {
      dates: "Dates and location",
      vehicle: "Vehicle",
      details: "Your details",
      payment: "Payment",
      check: "Check",
      confirmation: "Confirmation",
    },
    common: {
      continue: "Continue",
      back: "Back",
      edit: "Edit",
      loading: "Loading your booking…",
      startOver: "Start over",
    },
    dates: {
      title: "Choose your dates and location",
      description: "Tell us where and when you need the car.",
      pickupLocation: "Pick-up location",
      locationPlaceholder: "Paste a Google Maps link, or type an address",
      locationHint: "For example a hotel, airport terminal or barangay.",
      differentReturn: "Return to a different location",
      returnLocation: "Return location",
      pickupDate: "Pick-up date",
      pickupTime: "Pick-up time",
      returnDate: "Return date",
      returnTime: "Return time",
    },
    vehicle: {
      title: "Choose your vehicle",
      description: "Booking is open: choose any vehicle. Prices shown are per day for your dates.",
      select: "Select",
      selected: "Selected",
      notAvailable: "Not available right now",
      selectPrompt: "Select a vehicle to continue.",
      selectedUnavailable: "Your selected vehicle is not available right now. Please choose another one.",
      loadError: "We could not load the vehicles.",
      vehiclesLabel: "Available vehicles",
    },
    details: {
      title: "Your details",
      description: "We use these to prepare your rental.",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      license: "Driver's license number",
      licenseHint: "The main driver needs a valid license at pick-up.",
      notes: "Special requests (optional)",
    },
    payment: {
      title: "Payment",
      description: "Choose how you would like to pay. This is a demo, so no real payment is taken.",
      methodLabel: "Payment method",
      methods: {
        card: { label: "Credit or debit card", description: "Pay with your card." },
        gcash: { label: "GCash", description: "Pay with your GCash wallet." },
        maya: { label: "Maya", description: "Pay with your Maya wallet." },
        paypal: { label: "PayPal", description: "Pay with your PayPal account." },
        wise: { label: "Wise", description: "Pay with your Wise account." },
        pay_at_pickup: {
          label: "Pay at pick-up",
          description: "Placeholder: pay when you collect the vehicle.",
        },
      },
      cardNotice:
        "Card details are entered on the payment provider's secure page, never on this website. In this demo no card details are asked for.",
      redirectNotice: (method: string) =>
        `You would be sent to ${method} to approve the payment. In this demo, this step is simulated.`,
      pickupNotice:
        "You pay when you collect the vehicle. Your booking stays pending until our team confirms it.",
      pay: (amount: string) => `Pay ${amount} and confirm booking`,
      confirmPickup: "Confirm booking",
      terms: "I agree to the rental terms and conditions",
      termsError: "Please accept the terms to continue.",
      processing: "Processing your payment. Please do not close this page.",
      failedTitle: "Payment failed",
      failureReasons: {
        declined: "The payment was declined.",
        cancelled: "The payment was cancelled.",
        insufficient_funds: "There were not enough funds.",
      },
      errors: {
        price_changed: {
          title: "The price has changed",
          body: "The daily rate changed while you were checking out. You have not been charged. Please check the new total.",
          action: "Check your booking",
        },
        not_found: {
          title: "We could not find that vehicle",
          body: "Please choose a vehicle again.",
          action: "Choose a vehicle",
        },
        unknown: {
          title: "We could not confirm your booking",
          body: "Something went wrong. Please try again.",
          action: "",
        },
      },
      tryAgain: "Try again",
      demo: {
        title: "Demo controls",
        description: "Only shown in this demo. Choose what the mock payment does.",
        success: "The payment succeeds",
        decline: "The payment is declined",
      },
    },
    check: {
      title: "Check your booking",
      description: "Check everything below. You will pay and confirm on the next step.",
      toPayment: "Continue to payment",
    },
    summary: {
      title: "Booking summary",
      vehicle: "Vehicle",
      noVehicle: "No vehicle selected yet",
      pickup: "Pick-up",
      return: "Return",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      rate: (rate: string, days: number) => `${rate} × ${days} ${days === 1 ? "day" : "days"}`,
      vehicleLine: "Vehicle rental",
      total: "Total",
      driver: "Driver",
      payment: "Payment",
      pricesNote: "All prices are in PHP and include VAT.",
    },
    confirmation: {
      titleConfirmed: "Booking confirmed",
      titlePending: "Booking received",
      subtitleConfirmed: "Thank you. Your payment was received and your booking is confirmed.",
      subtitlePending: "Thank you. Our team will confirm your booking shortly. You pay at pick-up.",
      reference: "Booking reference",
      referenceHint: "Keep this number. You will need it at pick-up.",
      statusLabel: "Status",
      nextTitle: "What happens next",
      nextSteps: [
        "Placeholder: we email you a confirmation with all the details.",
        "Placeholder: bring your driver's license and this reference to the pick-up point.",
        "Placeholder: return the vehicle at the agreed time and place.",
      ],
      toHome: "Back to home",
      browse: "Browse more vehicles",
      notFoundTitle: "Booking not found",
      notFoundDescription: "We could not find a booking with that reference.",
    },
  },

  contact: {
    meta: {
      title: "Contact us",
      description: "Placeholder description: call, email or send us a message and we will get back to you.",
    },
    title: "Contact us",
    subtitle: "Questions about a rental? Send us a message.",
    details: {
      title: "Get in touch",
      phone: "Phone",
      email: "Email",
      address: "Address",
      hours: "Opening hours",
      addressValue: "Unit 000, Placeholder Building, Makati City, Metro Manila",
      hoursValue: "Daily, 7:00 AM to 9:00 PM",
    },
    form: {
      title: "Send us a message",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      vehicle: "Vehicle you are interested in (optional)",
      vehicleNone: "No preference",
      vehiclesLoading: "Loading vehicles…",
      message: "Message",
      consent: "I agree to be contacted about my inquiry",
      submit: "Send message",
      sending: "Sending",
      successTitle: "Message sent",
      successBody: "Thank you. We will get back to you soon.",
      sendAnother: "Send another message",
      errorTitle: "We could not send your message",
      errorBody: "Please check your details and try again.",
    },
  },
  admin: {
    meta: { titleTemplate: "%s | Admin" },
    nav: {
      label: "Admin navigation",
      dashboard: "Dashboard",
      customers: "Customers",
      leads: "Leads",
      pipeline: "Pipeline",
      tasks: "Tasks",
      bookings: "Bookings",
      reports: "Reports",
      pricing: "Pricing",
      reviews: "Reviews",
      users: "Users",
      roles: "Roles",
      viewSite: "View website",
    },
    frame: {
      brand: "Admin",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      signedInAs: "Signed in as",
      logout: "Log out",
      loggingOut: "Logging out",
      loading: "Loading your account…",
    },
    login: {
      title: "Staff login",
      description: "Sign in to manage customers, leads and bookings.",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      submitting: "Signing in",
      backToSite: "Back to the website",
      errors: {
        invalid_credentials: "Wrong email or password.",
        account_inactive: "This account is deactivated. Ask an admin to turn it back on.",
        forbidden: "You do not have access.",
        unknown: "We could not sign you in. Please try again.",
      },
      demo: {
        title: "Demo accounts",
        description: "Only shown in this demo. Every account uses the same password:",
        use: "Use this account",
        accounts: [
          { role: "Admin", email: "admin@carrental.example" },
          { role: "Sales", email: "liza.manalo@carrental.example" },
          { role: "Accountant", email: "accounting@carrental.example" },
          { role: "Operations", email: "operations@carrental.example" },
        ],
      },
    },
    forbidden: {
      title: "You do not have access to this page",
      description: "Your role does not include this area. Ask an admin if you need it.",
      action: "Go to my start page",
    },
    common: {
      search: "Search",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving",
      add: "Add",
      back: "Back",
      created: "Created",
      updated: "Updated",
      none: "None",
      unassigned: "Unassigned",
      any: "Any",
      noResultsTitle: "No results",
      noResultsDescription: "Try a different search or remove a filter.",
      clearFilters: "Clear filters",
      showingRange: (from: number, to: number, total: number) => `Showing ${from} to ${to} of ${total}`,
      loadError: "We could not load this.",
      notFoundTitle: "Not found",
      notFoundDescription: "This record does not exist or was deleted.",
      confirmDelete: "Delete",
      noPermission: "You do not have permission to do this.",
      saveError: "We could not save your changes. Please try again.",
      saved: "Changes saved",
    },
    dashboard: {
      title: "Dashboard",
      welcome: (name: string) => `Welcome back, ${name}.`,
      cards: {
        leads: "Open leads",
        newLeads: "New leads",
        customers: "Customers",
        activeBookings: "Active bookings",
        pendingBookings: "Pending bookings",
        tasks: "Open tasks",
      },
      cardHints: {
        tasks: (overdue: number) => (overdue === 0 ? "None overdue" : `${overdue} overdue`),
        leads: "Not yet won or lost",
        newLeads: "Waiting for a first contact",
        customers: "In your database",
        activeBookings: "Cars out right now",
        pendingBookings: "Waiting for confirmation",
      },
      leadsByStage: "Leads by stage",
      recentActivity: "Recent activity",
      noActivityTitle: "No activity yet",
      noActivityDescription: "Notes, calls and status changes will appear here.",
      cardsLabel: "Summary",
    },
    customers: {
      title: "Customers",
      description: "Everyone who has booked or was added by your team.",
      searchLabel: "Search customers",
      searchPlaceholder: "Search by name, phone or email",
      columns: { name: "Name", phone: "Phone", email: "Email", bookings: "Bookings", added: "Added" },
      add: "Add customer",
      emptyTitle: "No customers yet",
      emptyDescription: "Customers appear here when they book, or when you add them.",
      form: {
        addTitle: "Add customer",
        editTitle: "Edit customer",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        phoneHint: "For example 0917 123 4567",
        license: "Driver's license number (optional)",
        notes: "Notes",
        duplicateEmail: "A customer with this email already exists.",
      },
      saved: "Customer saved",
      added: "Customer added",
      deleted: "Customer deleted",
      deleteTitle: "Delete this customer?",
      deleteDescription: "This removes the customer and their activity log. It cannot be undone.",
      deleteBlocked: "This customer has bookings, so they cannot be deleted.",
      profile: {
        back: "All customers",
        tabs: { details: "Details", bookings: "Booking history", activity: "Activity" },
        details: "Details",
        contactPerson: "Contact",
        license: "Driver's license",
        notes: "Notes",
        noNotes: "No notes yet.",
        bookings: "Booking history",
        noBookings: "No bookings yet.",
        bookingColumns: { reference: "Reference", vehicle: "Vehicle", dates: "Dates", total: "Total", status: "Status" },
        activity: "Activity",
        customerSince: "Customer since",
      },
    },
    contacts: {
      title: "More contact details",
      description: "Extra phone numbers and emails for this person.",
      add: "Add contact detail",
      empty: "No extra contact details yet.",
      type: "Type",
      label: "Label",
      labelPlaceholder: "e.g. Office, Assistant",
      value: "Phone number or email",
      addTitle: "Add contact detail",
      editTitle: "Edit contact detail",
      deleteTitle: "Delete this contact detail?",
      types: { phone: "Phone", email: "Email" },
      invalidPhone: "Enter a valid phone number.",
      invalidEmail: "Enter a valid email address.",
    },
    leads: {
      title: "Leads",
      description: "People who have asked about a rental. Move them from New to Won or Lost.",
      searchLabel: "Search leads",
      searchPlaceholder: "Search by name, phone or email",
      filters: { stage: "Stage", source: "Source", assignee: "Assigned to" },
      columns: { name: "Name", contact: "Contact", source: "Source", stage: "Stage", vehicle: "Vehicle", assignee: "Assigned to", created: "Created" },
      add: "Add lead",
      emptyTitle: "No leads yet",
      emptyDescription: "Leads from the website contact form and the ones you add show up here.",
      form: {
        addTitle: "Add lead",
        editTitle: "Edit lead",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        source: "Source",
        stage: "Stage",
        vehicle: "Vehicle they are interested in",
        noVehicle: "No preference",
        assignee: "Assigned to",
        message: "What they asked for",
      },
      saved: "Lead saved",
      added: "Lead added",
      deleted: "Lead deleted",
      deleteTitle: "Delete this lead?",
      deleteDescription: "This removes the lead and its activity log. It cannot be undone.",
      detail: {
        back: "All leads",
        details: "Details",
        stage: "Stage",
        changeStage: "Change stage",
        stageChanged: "Stage updated",
        assignee: "Assigned to",
        source: "Source",
        vehicle: "Vehicle interest",
        message: "Message",
        noMessage: "No message.",
        created: "Created",
        activity: "Activity",
        customerLinked: "Customer record",
        viewCustomer: "View customer",
        convert: "Convert to customer",
        convertHint: "Creates a customer from this lead and marks it Won.",
        converted: "Customer created and lead marked Won",
        convertTitle: "Convert this lead?",
        convertDescription: "A customer record is created from this lead's details, and the lead is marked as Won.",
      },
      stageChangeNote: (from: string, to: string) => `Stage changed from ${from} to ${to}.`,
      createdNote: "Lead added by staff.",
      convertNote: "Converted to a customer.",
    },
    bookings: {
      title: "Bookings",
      description: "Every rental, from a new booking to a returned car.",
      searchLabel: "Search bookings",
      searchPlaceholder: "Search by reference, customer or vehicle",
      filters: { status: "Status" },
      columns: {
        reference: "Reference",
        customer: "Customer",
        vehicle: "Vehicle",
        pickup: "Pick-up",
        return: "Return",
        total: "Total",
        status: "Status",
        payment: "Payment",
      },
      emptyTitle: "No bookings yet",
      emptyDescription: "Bookings made on the website appear here.",
      detail: {
        back: "All bookings",
        booked: "Booked on",
        trip: "Trip",
        customer: "Customer",
        viewCustomer: "View customer",
        payment: "Payment",
        method: "Method",
        amount: "Amount",
        status: "Status",
        providerRef: "Provider reference",
        notes: "Customer notes",
        noNotes: "No notes.",
        markPaid: "Mark payment as received",
        paymentReceived: "Payment marked as received",
        statusChanged: "Booking status updated",
        priceNote: "These are the prices this booking was made at.",
        nextStep: "Next step",
        finalStatus: "This booking is final. Its status cannot change.",
        actions: {
          confirmed: "Confirm booking",
          active: "Start rental (car picked up)",
          completed: "Complete rental (car returned)",
          cancelled: "Cancel booking",
        },
        cancelTitle: "Cancel this booking?",
        cancelDescription: "The vehicle becomes available again for these dates. This cannot be undone.",
        cancelConfirm: "Cancel booking",
        keep: "Keep booking",
        invalidMove: "That status change is not allowed.",
      },
      statusChangeNote: (reference: string, from: string, to: string) =>
        `Booking ${reference} changed from ${from} to ${to}.`,
      paymentNote: (reference: string, amount: string, method: string) =>
        `Payment of ${amount} (${method}) for booking ${reference} marked as received.`,
    },
    pricing: {
      title: "Vehicle prices",
      description:
        "Change a vehicle's daily rate. New bookings use the new rate. Existing bookings keep the price they were made at.",
      columns: { vehicle: "Vehicle", category: "Category", rate: "Daily rate", status: "Status", actions: "Actions" },
      change: "Change price",
      modalTitle: (name: string) => `Change price: ${name}`,
      currentRate: (rate: string) => `Current rate: ${rate} per day`,
      rateLabel: "New daily rate (PHP)",
      rateHint: "A whole number of pesos, per day.",
      invalid: "Enter a whole number between 100 and 100,000.",
      noChange: "The new rate is the same as the current one.",
      impact: "Existing bookings keep their price. Only new bookings use the new rate.",
      saved: "Price updated",
      empty: "No vehicles found.",
    },
    reviews: {
      title: "Reviews",
      description: "What customers wrote about our service. Only the reviews switched on here appear on the website.",
      columns: { customer: "Customer", rating: "Rating", comment: "Comment", reference: "Booking", date: "Date", show: "On website" },
      showSwitch: (name: string) => `Show ${name}'s review on the website`,
      shown: "Shown",
      hidden: "Hidden",
      shownToast: "Review is now shown on the website",
      hiddenToast: "Review is now hidden from the website",
      emptyTitle: "No reviews yet",
      emptyDescription: "Reviews from customers will appear here.",
    },
    permissions: {
      groups: {
        dashboard: "Dashboard",
        customers: "Customers",
        leads: "Leads and pipeline",
        tasks: "Tasks",
        bookings: "Bookings",
        money: "Reports and prices",
        reviews: "Reviews",
        admin: "Administration",
      },
      items: {
        "dashboard.view": { label: "View the dashboard", description: "See summary numbers and recent activity." },
        "customers.view": { label: "View customers", description: "See the customer list, profiles and booking history." },
        "customers.edit": { label: "Add, edit and delete customers", description: "Also covers their extra contact details." },
        "leads.view": { label: "View leads and the pipeline", description: "See leads and the pipeline board." },
        "leads.edit": { label: "Add, edit and move leads", description: "Change stages, convert leads to customers, delete leads." },
        "tasks.manage": { label: "Manage tasks", description: "Add, edit, finish and delete tasks and follow-ups." },
        "bookings.view": { label: "View bookings", description: "See bookings, payments and prices." },
        "bookings.edit": { label: "Change booking status", description: "Confirm, start, complete or cancel bookings and record payments." },
        "reports.view": { label: "View reports", description: "See leads, customers, bookings and revenue reports." },
        "pricing.edit": { label: "Change vehicle prices", description: "Set the daily rate for new bookings." },
        "reviews.manage": { label: "Manage reviews", description: "Read customer reviews and choose which ones show on the website." },
        "users.manage": { label: "Manage users", description: "Add and edit staff accounts and turn them on or off." },
        "roles.manage": { label: "Manage roles", description: "Create roles and choose what each role can do." },
      },
    },
    users: {
      title: "Users",
      description: "Staff accounts. Each person has one role, and the role decides what they can do.",
      columns: { name: "Name", email: "Email", role: "Role", status: "Status", actions: "Actions" },
      statuses: { active: "Active", inactive: "Inactive" },
      you: "(you)",
      add: "Add user",
      form: {
        addTitle: "Add user",
        editTitle: "Edit user",
        name: "Full name",
        email: "Email",
        role: "Role",
        rolePlaceholder: "Choose a role",
        active: "This account is active",
        passwordNote: "Demo only: every account signs in with the password demo1234.",
      },
      roleChangeNote: "A change of role applies the next time the person signs in.",
      added: "User added",
      saved: "User saved",
      deactivate: "Deactivate",
      reactivate: "Reactivate",
      deactivated: "User deactivated",
      reactivated: "User reactivated",
      deactivateTitle: (name: string) => `Deactivate ${name}?`,
      deactivateDescription: "They will no longer be able to sign in. Their records stay.",
      emptyTitle: "No users yet",
      errors: {
        duplicate_email: "Another user already has this email.",
        last_admin: "There must always be at least one active user who can manage users and roles.",
        self_deactivate: "You cannot deactivate your own account.",
        unknown: "We could not save your changes. Please try again.",
      },
    },
    roles: {
      title: "Roles",
      description: "A role is a set of things a person is allowed to do. Choose which roles can do what.",
      applyNote: "Changes to a role apply the next time each person signs in.",
      add: "Add role",
      columns: { name: "Role", description: "Description", permissions: "Can do", users: "People", actions: "Actions" },
      permissionCount: (n: number, total: number) => `${n} of ${total}`,
      builtIn: "Built in",
      form: {
        addTitle: "Add role",
        editTitle: "Edit role",
        name: "Role name",
        description: "Description",
        permissions: "What this role can do",
        lockedNote: "The Admin role always has full access and cannot be changed or deleted.",
        editNeedsView: "Choosing an edit permission also turns on the matching view permission.",
        permissionsRequired: "Choose at least one permission.",
      },
      deleteHint: "A role can only be deleted when nobody uses it.",
      added: "Role added",
      saved: "Role saved",
      deleted: "Role deleted",
      deleteTitle: (name: string) => `Delete the ${name} role?`,
      deleteDescription: "This cannot be undone. A role that people are still using cannot be deleted.",
      errors: {
        duplicate_name: "A role with this name already exists.",
        has_users: "People are still using this role. Move them to another role first.",
        system_role: "The Admin role cannot be changed or deleted.",
        last_admin: "There must always be at least one active user who can manage users and roles.",
        unknown: "We could not save your changes. Please try again.",
      },
    },
    reports: {
      title: "Reports",
      description: "A simple look at leads, customers, bookings and revenue.",
      range: {
        title: "Date range",
        from: "From",
        to: "To",
        presets: { last30: "Last 30 days", last6Months: "Last 6 months", thisYear: "This year" },
        presetsLabel: "Quick ranges",
        invalid: "The start date must be on or before the end date.",
      },
      summary: {
        label: "Summary for this period",
        leads: "Leads",
        customers: "New customers",
        bookings: "Bookings",
        revenue: "Revenue",
        leadsHint: "Created in this period",
        customersHint: "Added in this period",
        bookingsHint: "Picked up in this period",
        revenueHint: "Confirmed, active and completed",
      },
      tabs: { chart: "Chart", table: "Table" },
      month: "Month",
      leadsByStage: {
        title: "Leads by status",
        description: "Leads created in this period, by the stage they are in now.",
        chartLabel: "Leads by status",
        stage: "Stage",
        count: "Leads",
      },
      overTime: {
        title: "New leads and customers",
        description: "How many were added each month.",
        chartLabel: "New leads and new customers per month",
        leads: "Leads",
        customers: "Customers",
      },
      revenue: {
        title: "Bookings and revenue",
        description:
          "By pick-up month. Revenue counts confirmed, active and completed bookings. Pending and cancelled ones are left out.",
        chartLabel: "Revenue per month",
        bookings: "Bookings",
        revenue: "Revenue",
        total: "Total",
      },
      scroll: (label: string) => `${label}. Scroll sideways to see all of it.`,
    },
    tasks: {
      title: "Tasks",
      description: "Follow-ups and to-dos for your team.",
      searchLabel: "Search tasks",
      searchPlaceholder: "Search by task, person or assignee",
      filters: { status: "Status", assignee: "Assigned to", mine: "Assigned to me" },
      statuses: { open: "Open", done: "Done", all: "All" },
      columns: { done: "Done", title: "Task", due: "Due", assignee: "Assigned to", linked: "About", actions: "Actions" },
      add: "Add task",
      emptyTitle: "No tasks here",
      emptyDescription: "Add a follow-up so nothing gets forgotten.",
      overdue: "Overdue",
      dueToday: "Due today",
      markDone: (title: string) => `Mark done: ${title}`,
      markOpen: (title: string) => `Mark not done: ${title}`,
      form: {
        addTitle: "Add task",
        editTitle: "Edit task",
        title: "What needs doing?",
        due: "Due date",
        assignee: "Assigned to",
        linkType: "About",
        linkNone: "Nothing in particular",
        linkLead: "A lead",
        linkCustomer: "A customer",
        linkTarget: "Which one?",
        choose: "Choose…",
        notes: "Notes",
        linkRequired: "Choose who this task is about.",
        dueRequired: "Choose a due date.",
      },
      added: "Task added",
      saved: "Task saved",
      deleted: "Task deleted",
      doneToast: "Task marked done",
      reopenedToast: "Task reopened",
      deleteTitle: "Delete this task?",
      deleteDescription: "This cannot be undone.",
      linkedCard: {
        title: "Tasks",
        description: "Follow-ups linked to this record.",
        empty: "No tasks yet.",
        add: "Add task",
        viewAll: "View all tasks",
      },
      completedNote: (title: string) => `Task completed: ${title}`,
    },
    pipeline: {
      title: "Pipeline",
      description: "Move leads from New to Won or Lost. Drag a card by its handle, or use the Move to menu.",
      boardLabel: "Lead pipeline",
      assigneeFilter: "Assigned to",
      columnCount: (n: number) => `${n} ${n === 1 ? "lead" : "leads"}`,
      emptyColumn: "No leads",
      moveTo: "Move to",
      dragHandle: (name: string) => `Drag ${name} to another stage`,
      readOnly: "You can view the pipeline but not move leads.",
      moved: (name: string, stage: string) => `${name} moved to ${stage}`,
      moveFailed: "The lead could not be moved. Please try again.",
      openLead: "Open lead",
      total: (n: number) => `${n} ${n === 1 ? "lead" : "leads"} in the pipeline`,
    },
    activities: {
      title: "Activity log",
      add: "Add activity",
      type: "Type",
      body: "What happened",
      bodyPlaceholder: "Write a note or summarize the call",
      submit: "Add to log",
      submitting: "Adding",
      empty: "No activity yet.",
      system: "Website",
      by: "by",
      added: "Activity added",
      errorRequired: "Please write something.",
      related: { lead: "Lead", customer: "Customer" },
    },
  },
} as const;

export type Content = typeof content;
