/**
 * ALL user-facing copy lives here. Components import `content` instead of
 * hardcoding text, so wording can be changed (or translated later) in one place.
 * As pages are added, add their sections below.
 */
export const content = {
  site: {
    name: "Car Rental Co.",
    tagline: "Placeholder tagline goes here",
    description:
      "Placeholder description: rent a car in the Philippines with simple online booking.",
    contactPhone: "+63 917 000 0000",
    contactEmail: "hello@example.com",
  },

  seo: {
    titleTemplate: "%s | Car Rental Co.",
    defaultTitle: "Car Rental Co. | Rent a car in the Philippines",
    locale: "en_PH",
  },

  nav: {
    public: [
      { label: "Home", href: "/" },
      { label: "Vehicles", href: "/vehicles" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    bookCta: { label: "Book now", href: "/book/dates" },
    primaryLabel: "Main navigation",
    skipToContent: "Skip to main content",
  },

  socials: [
    { label: "Facebook", href: "https://facebook.com" },
    { label: "Instagram", href: "https://instagram.com" },
    { label: "TikTok", href: "https://tiktok.com" },
  ],

  footer: {
    columns: [
      {
        title: "Explore",
        links: [
          { label: "Vehicles", href: "/vehicles" },
          { label: "Book now", href: "/book/dates" },
          { label: "About us", href: "/about" },
        ],
      },
      {
        title: "Support",
        links: [
          { label: "Contact us", href: "/contact" },
          { label: "Staff login", href: "/admin/login" },
        ],
      },
    ],
    socialsTitle: "Follow us",
    legal: "© 2026 Car Rental Co. All rights reserved.",
  },

  /** Built-in labels used inside UI kit components (mostly accessibility text). */
  ui: {
    loading: "Loading…",
    close: "Close",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    previousMonth: "Go to previous month",
    nextMonth: "Go to next month",
    selectDate: "Select date",
    selectTime: "Select time",
    dismiss: "Dismiss",
    required: "required",
    opensInNewTab: "opens in a new tab",
    notifications: "Notifications",
    pagination: {
      label: "Pagination",
      previous: "Previous",
      next: "Next",
      page: "Page",
    },
    stepper: { label: "Progress", step: "Step", of: "of", complete: "completed" },
    sort: { ascending: "sorted ascending", descending: "sorted descending" },
    alert: {
      info: "Note",
      success: "Success",
      warning: "Warning",
      danger: "Error",
    },
  },

  /** Wording for the reusable empty / error / loading states. */
  states: {
    emptyTitle: "Nothing here yet",
    emptyDescription: "There is nothing to show right now.",
    errorTitle: "Something went wrong",
    errorDescription: "We could not load this. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundDescription: "The page you are looking for does not exist or has moved.",
    backHome: "Back to home",
  },

  /** Form error messages. Used by every Zod schema. */
  validation: {
    required: "This field is required.",
    email: "Enter a valid email address.",
    phone: "Enter a valid mobile number, e.g. 0917 123 4567.",
    messageTooShort: "Please write at least 10 characters.",
    dateInPast: "Choose today or a future date.",
    returnBeforePickup: "Return must be after pick-up.",
    consent: "Please tick this box to continue.",
    license: "Enter your driver's license number.",
  },

  /** The words shown for each id in /src/lib/constants.ts. */
  enums: {
    vehicleCategory: {
      sedan: "Sedan",
      hatchback: "Hatchback",
      suv: "SUV",
      mpv: "MPV",
      van: "Van",
      pickup: "Pickup",
    },
    transmission: { automatic: "Automatic", manual: "Manual" },
    fuel: { gasoline: "Gasoline", diesel: "Diesel", hybrid: "Hybrid", electric: "Electric" },
    vehicleStatus: { available: "Available", maintenance: "In maintenance", inactive: "Inactive" },
    leadStage: { new: "New", contacted: "Contacted", qualified: "Qualified", won: "Won", lost: "Lost" },
    leadSource: {
      website: "Website",
      phone: "Phone",
      walk_in: "Walk-in",
      facebook: "Facebook",
      referral: "Referral",
    },
    activityType: { note: "Note", call: "Call", status_change: "Status change" },
    bookingStatus: {
      pending: "Pending",
      confirmed: "Confirmed",
      active: "Active",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    paymentMethod: {
      card: "Credit or debit card",
      gcash: "GCash",
      maya: "Maya",
      pay_at_pickup: "Pay at pick-up",
    },
    paymentStatus: { pending: "Pending", processing: "Processing", paid: "Paid", failed: "Failed" },
  },

  quickSearch: {
    title: "Find your car",
    pickupLocation: "Pick-up location",
    locationPlaceholder: "Choose a location",
    pickupDate: "Pick-up date",
    pickupTime: "Pick-up time",
    returnDate: "Return date",
    returnTime: "Return time",
    submit: "Search vehicles",
  },

  home: {
    meta: {
      description:
        "Placeholder description: browse our cars, pick your dates and book online in minutes. Prices in PHP.",
    },
    hero: {
      title: "Rent a car in the Philippines",
      subtitle: "Placeholder: simple online booking with clear daily prices in PHP.",
    },
    featured: {
      title: "Featured vehicles",
      description: "A few of our most popular cars.",
      viewAll: "View all vehicles",
    },
    howItWorks: {
      title: "How it works",
      steps: [
        { title: "Choose dates and place", body: "Tell us when and where you need the car." },
        { title: "Pick your vehicle", body: "Compare cars and add any extras you want." },
        { title: "Book and pay", body: "Confirm your details and pay online or at pick-up." },
        { title: "Pick up and go", body: "Show your booking reference and drive away." },
      ],
    },
    testimonials: {
      title: "What customers say",
      description: "Placeholder section. Real reviews will be added here.",
      items: [
        { quote: "Placeholder testimonial. A real customer review goes here.", name: "Customer name", detail: "Trip type" },
        { quote: "Placeholder testimonial. A real customer review goes here.", name: "Customer name", detail: "Trip type" },
        { quote: "Placeholder testimonial. A real customer review goes here.", name: "Customer name", detail: "Trip type" },
      ],
    },
    cta: {
      title: "Ready to hit the road?",
      description: "Pick your dates and book in a few minutes.",
      button: "Book now",
    },
  },

  about: {
    meta: {
      title: "About us",
      description: "Placeholder description: learn about our company, our values and our team.",
    },
    title: "About us",
    subtitle: "Placeholder: a short line about the company.",
    story: {
      title: "Our story",
      body: [
        "Placeholder: tell the story of the company here. Who started it, when, and why.",
        "Placeholder: a second paragraph about the fleet, the service and what makes customers come back.",
      ],
    },
    values: {
      title: "What we stand for",
      items: [
        { title: "Reliable vehicles", body: "Placeholder: how the fleet is maintained and checked." },
        { title: "Clear pricing", body: "Placeholder: daily rates in PHP with no surprises." },
        { title: "Friendly service", body: "Placeholder: how the team looks after customers." },
      ],
    },
    team: {
      title: "Meet the team",
      members: [
        { name: "Team member", role: "Role" },
        { name: "Team member", role: "Role" },
        { name: "Team member", role: "Role" },
      ],
    },
    cta: { title: "Questions before you book?", button: "Contact us" },
  },

  vehicles: {
    meta: {
      title: "Our vehicles",
      description:
        "Placeholder description: compare sedans, SUVs, vans and pickups with clear daily rates in PHP.",
    },
    title: "Our vehicles",
    description: "Filter by type, price, transmission, seats and fuel. Share the page to share your search.",
    filtersTitle: "Filters",
    showFilters: "Show filters",
    hideFilters: "Hide filters",
    filters: {
      category: "Category",
      transmission: "Transmission",
      fuel: "Fuel type",
      minSeats: "Seats",
      minPrice: "Min price per day",
      maxPrice: "Max price per day",
      any: "Any",
      noMinimum: "No minimum",
      noMaximum: "No maximum",
      seatsOrMore: (n: number) => `${n}+ seats`,
    },
    sortLabel: "Sort by",
    sorts: {
      "price-asc": "Price: low to high",
      "price-desc": "Price: high to low",
      "name-asc": "Name: A to Z",
      "seats-desc": "Seats: most first",
    },
    resultCount: (n: number) => `${n} ${n === 1 ? "vehicle" : "vehicles"} found`,
    clearFilters: "Clear filters",
    emptyTitle: "No vehicles match your filters",
    emptyDescription: "Try removing a filter or choosing a different price range.",
    trip: {
      title: "Your trip",
      pickup: "Pick-up",
      return: "Return",
      change: "Change search",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
    },
    resultsLabel: "Vehicle results",
  },

  vehicleCard: {
    perDay: "per day",
    totalFor: (days: number) => `Total for ${days} ${days === 1 ? "day" : "days"}`,
    viewDetails: "View details",
    bookNow: "Book now",
    seats: (n: number) => `${n} seats`,
    unavailable: "Unavailable",
  },

  vehicleDetail: {
    back: "All vehicles",
    perDay: "per day",
    description: "About this vehicle",
    specsTitle: "Specifications",
    specs: {
      category: "Category",
      transmission: "Transmission",
      fuel: "Fuel type",
      seats: "Seats",
      year: "Year",
    },
    featuresTitle: "Features",
    availabilityTitle: "Availability",
    availableNow: "Available to book",
    unavailableNow: "Not available right now",
    bookNow: "Book now",
    askAbout: "Ask about this vehicle",
    galleryLabel: "Vehicle photos",
    viewPhoto: (n: number) => `View photo ${n}`,
    metaFallbackTitle: "Vehicle",
    metaDescription: (name: string, rate: string) =>
      `Rent the ${name} for ${rate} per day. Book online with clear pricing.`,
  },

  booking: {
    meta: {
      title: "Book your car",
      description: "Book your rental car online in a few simple steps.",
    },
    steps: {
      dates: "Dates and location",
      vehicle: "Vehicle and extras",
      details: "Your details",
      payment: "Payment",
      review: "Review",
      confirmation: "Confirmation",
    },
    common: {
      continue: "Continue",
      back: "Back",
      edit: "Edit",
      loading: "Loading your booking…",
      startOver: "Start over",
    },
    dates: {
      title: "Choose your dates and location",
      description: "Tell us where and when you need the car.",
      pickupLocation: "Pick-up location",
      locationPlaceholder: "Choose a location",
      differentReturn: "Return to a different location",
      returnLocation: "Return location",
      pickupDate: "Pick-up date",
      pickupTime: "Pick-up time",
      returnDate: "Return date",
      returnTime: "Return time",
    },
    vehicle: {
      title: "Choose your vehicle",
      description: "Vehicles shown are for your dates. Prices are per day.",
      select: "Select",
      selected: "Selected",
      unavailable: "Unavailable for these dates",
      extrasTitle: "Optional extras",
      extrasDescription: "Add anything you need. You can change this later.",
      extraPerDay: "per day",
      extraFlat: "one time",
      selectPrompt: "Select a vehicle to continue.",
      selectedUnavailable: "Your selected vehicle is not available for these dates. Please choose another one.",
      loadError: "We could not load the vehicles.",
      vehiclesLabel: "Available vehicles",
      extrasLabel: "Extras",
    },
    details: {
      title: "Your details",
      description: "We use these to prepare your rental.",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      license: "Driver's license number",
      licenseHint: "The main driver needs a valid license at pick-up.",
      notes: "Special requests (optional)",
    },
    payment: {
      title: "Payment",
      description: "Choose how you would like to pay. This is a demo, so no real payment is taken.",
      methodLabel: "Payment method",
      methods: {
        card: { label: "Credit or debit card", description: "Pay with your card." },
        gcash: { label: "GCash", description: "Pay with your GCash wallet." },
        maya: { label: "Maya", description: "Pay with your Maya wallet." },
        pay_at_pickup: {
          label: "Pay at pick-up",
          description: "Placeholder: pay when you collect the vehicle.",
        },
      },
      cardNotice:
        "Card details are entered on the payment provider's secure page, never on this website. In this demo no card details are asked for.",
      redirectNotice: (method: string) =>
        `You would be sent to ${method} to approve the payment. In this demo, this step is simulated.`,
      pickupNotice:
        "You pay when you collect the vehicle. Your booking stays pending until our team confirms it.",
      pay: (amount: string) => `Pay ${amount}`,
      choosePickup: "Choose pay at pick-up",
      processing: "Processing your payment. Please do not close this page.",
      successTitle: "Payment successful",
      successBody: (amount: string) => `We received ${amount}.`,
      pickupTitle: "Pay at pick-up selected",
      pickupBody: "Nothing to pay right now.",
      failedTitle: "Payment failed",
      failureReasons: {
        declined: "The payment was declined.",
        cancelled: "The payment was cancelled.",
        insufficient_funds: "There were not enough funds.",
      },
      tryAgain: "Try again",
      changeMethod: "Change payment method",
      continueToReview: "Continue to review",
      demo: {
        title: "Demo controls",
        description: "Only shown in this demo. Choose what the mock payment does.",
        success: "The payment succeeds",
        decline: "The payment is declined",
      },
    },
    review: {
      title: "Review and confirm",
      description: "Check everything below, then confirm your booking.",
      terms: "I agree to the rental terms and conditions",
      termsError: "Please accept the terms to confirm your booking.",
      confirm: "Confirm booking",
      confirming: "Confirming",
      errors: {
        vehicle_unavailable: {
          title: "This vehicle was just booked",
          body: "Someone else booked it for these dates while you were checking out. Please choose another vehicle.",
          action: "Choose another vehicle",
        },
        price_changed: {
          title: "The price has changed",
          body: "The daily rate changed since you paid. Please review the new total and pay again.",
          action: "Go to payment",
        },
        not_found: {
          title: "We could not find that vehicle",
          body: "Please choose a vehicle again.",
          action: "Choose a vehicle",
        },
        unknown: {
          title: "We could not confirm your booking",
          body: "Something went wrong. Please try again.",
          action: "",
        },
      },
    },
    summary: {
      title: "Booking summary",
      vehicle: "Vehicle",
      noVehicle: "No vehicle selected yet",
      pickup: "Pick-up",
      return: "Return",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      rate: (rate: string, days: number) => `${rate} × ${days} ${days === 1 ? "day" : "days"}`,
      vehicleLine: "Vehicle rental",
      extras: "Extras",
      total: "Total",
      driver: "Driver",
      payment: "Payment",
      pricesNote: "All prices are in PHP and include VAT.",
    },
    confirmation: {
      titleConfirmed: "Booking confirmed",
      titlePending: "Booking received",
      subtitleConfirmed: "Thank you. Your payment was received and your booking is confirmed.",
      subtitlePending: "Thank you. Our team will confirm your booking shortly. You pay at pick-up.",
      reference: "Booking reference",
      referenceHint: "Keep this number. You will need it at pick-up.",
      statusLabel: "Status",
      nextTitle: "What happens next",
      nextSteps: [
        "Placeholder: we email you a confirmation with all the details.",
        "Placeholder: bring your driver's license and this reference to the pick-up point.",
        "Placeholder: return the vehicle at the agreed time and place.",
      ],
      toHome: "Back to home",
      browse: "Browse more vehicles",
      notFoundTitle: "Booking not found",
      notFoundDescription: "We could not find a booking with that reference.",
    },
  },

  contact: {
    meta: {
      title: "Contact us",
      description: "Placeholder description: call, email or send us a message and we will get back to you.",
    },
    title: "Contact us",
    subtitle: "Questions about a rental? Send us a message.",
    details: {
      title: "Get in touch",
      phone: "Phone",
      email: "Email",
      address: "Address",
      hours: "Opening hours",
      addressValue: "Unit 000, Placeholder Building, Makati City, Metro Manila",
      hoursValue: "Daily, 7:00 AM to 9:00 PM",
    },
    form: {
      title: "Send us a message",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      vehicle: "Vehicle you are interested in (optional)",
      vehicleNone: "No preference",
      vehiclesLoading: "Loading vehicles…",
      message: "Message",
      consent: "I agree to be contacted about my inquiry",
      submit: "Send message",
      sending: "Sending",
      successTitle: "Message sent",
      successBody: "Thank you. We will get back to you soon.",
      sendAnother: "Send another message",
      errorTitle: "We could not send your message",
      errorBody: "Please check your details and try again.",
    },
  },
  admin: {
    meta: { titleTemplate: "%s | Admin" },
    nav: {
      label: "Admin navigation",
      dashboard: "Dashboard",
      customers: "Customers",
      leads: "Leads",
      viewSite: "View website",
    },
    frame: {
      brand: "Admin",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      signedInAs: "Signed in as",
      logout: "Log out",
      loggingOut: "Logging out",
      loading: "Loading your account…",
    },
    login: {
      title: "Staff login",
      description: "Sign in to manage customers, leads and bookings.",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      submitting: "Signing in",
      backToSite: "Back to the website",
      errors: {
        invalid_credentials: "Wrong email or password.",
        account_inactive: "This account is deactivated. Ask an admin to turn it back on.",
        forbidden: "You do not have access.",
        unknown: "We could not sign you in. Please try again.",
      },
      demo: {
        title: "Demo accounts",
        description: "Only shown in this demo. Every account uses the same password:",
        use: "Use this account",
        accounts: [
          { role: "Admin", email: "admin@carrental.example" },
          { role: "Sales", email: "liza.manalo@carrental.example" },
          { role: "Accountant", email: "accounting@carrental.example" },
          { role: "Operations", email: "operations@carrental.example" },
        ],
      },
    },
    forbidden: {
      title: "You do not have access to this page",
      description: "Your role does not include this area. Ask an admin if you need it.",
      action: "Go to my start page",
    },
    common: {
      search: "Search",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving",
      add: "Add",
      back: "Back",
      created: "Created",
      updated: "Updated",
      none: "None",
      unassigned: "Unassigned",
      any: "Any",
      noResultsTitle: "No results",
      noResultsDescription: "Try a different search or remove a filter.",
      clearFilters: "Clear filters",
      showingRange: (from: number, to: number, total: number) => `Showing ${from} to ${to} of ${total}`,
      loadError: "We could not load this.",
      notFoundTitle: "Not found",
      notFoundDescription: "This record does not exist or was deleted.",
      confirmDelete: "Delete",
      noPermission: "You do not have permission to do this.",
      saveError: "We could not save your changes. Please try again.",
      saved: "Changes saved",
    },
    dashboard: {
      title: "Dashboard",
      welcome: (name: string) => `Welcome back, ${name}.`,
      cards: {
        leads: "Open leads",
        newLeads: "New leads",
        customers: "Customers",
        activeBookings: "Active bookings",
        pendingBookings: "Pending bookings",
      },
      cardHints: {
        leads: "Not yet won or lost",
        newLeads: "Waiting for a first contact",
        customers: "In your database",
        activeBookings: "Cars out right now",
        pendingBookings: "Waiting for confirmation",
      },
      leadsByStage: "Leads by stage",
      recentActivity: "Recent activity",
      noActivityTitle: "No activity yet",
      noActivityDescription: "Notes, calls and status changes will appear here.",
      cardsLabel: "Summary",
    },
    customers: {
      title: "Customers",
      description: "Everyone who has booked or was added by your team.",
      searchLabel: "Search customers",
      searchPlaceholder: "Search by name, phone or email",
      columns: { name: "Name", phone: "Phone", email: "Email", bookings: "Bookings", added: "Added" },
      add: "Add customer",
      emptyTitle: "No customers yet",
      emptyDescription: "Customers appear here when they book, or when you add them.",
      form: {
        addTitle: "Add customer",
        editTitle: "Edit customer",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        phoneHint: "For example 0917 123 4567",
        license: "Driver's license number (optional)",
        notes: "Notes",
        duplicateEmail: "A customer with this email already exists.",
      },
      saved: "Customer saved",
      added: "Customer added",
      deleted: "Customer deleted",
      deleteTitle: "Delete this customer?",
      deleteDescription: "This removes the customer and their activity log. It cannot be undone.",
      deleteBlocked: "This customer has bookings, so they cannot be deleted.",
      profile: {
        back: "All customers",
        tabs: { details: "Details", bookings: "Booking history", activity: "Activity" },
        details: "Details",
        contactPerson: "Contact",
        license: "Driver's license",
        notes: "Notes",
        noNotes: "No notes yet.",
        bookings: "Booking history",
        noBookings: "No bookings yet.",
        bookingColumns: { reference: "Reference", vehicle: "Vehicle", dates: "Dates", total: "Total", status: "Status" },
        activity: "Activity",
        customerSince: "Customer since",
      },
    },
    contacts: {
      title: "More contact details",
      description: "Extra phone numbers and emails for this person.",
      add: "Add contact detail",
      empty: "No extra contact details yet.",
      type: "Type",
      label: "Label",
      labelPlaceholder: "e.g. Office, Assistant",
      value: "Phone number or email",
      addTitle: "Add contact detail",
      editTitle: "Edit contact detail",
      deleteTitle: "Delete this contact detail?",
      types: { phone: "Phone", email: "Email" },
      invalidPhone: "Enter a valid phone number.",
      invalidEmail: "Enter a valid email address.",
    },
    leads: {
      title: "Leads",
      description: "People who have asked about a rental. Move them from New to Won or Lost.",
      searchLabel: "Search leads",
      searchPlaceholder: "Search by name, phone or email",
      filters: { stage: "Stage", source: "Source", assignee: "Assigned to" },
      columns: { name: "Name", contact: "Contact", source: "Source", stage: "Stage", vehicle: "Vehicle", assignee: "Assigned to", created: "Created" },
      add: "Add lead",
      emptyTitle: "No leads yet",
      emptyDescription: "Leads from the website contact form and the ones you add show up here.",
      form: {
        addTitle: "Add lead",
        editTitle: "Edit lead",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        source: "Source",
        stage: "Stage",
        vehicle: "Vehicle they are interested in",
        noVehicle: "No preference",
        assignee: "Assigned to",
        message: "What they asked for",
      },
      saved: "Lead saved",
      added: "Lead added",
      deleted: "Lead deleted",
      deleteTitle: "Delete this lead?",
      deleteDescription: "This removes the lead and its activity log. It cannot be undone.",
      detail: {
        back: "All leads",
        details: "Details",
        stage: "Stage",
        changeStage: "Change stage",
        stageChanged: "Stage updated",
        assignee: "Assigned to",
        source: "Source",
        vehicle: "Vehicle interest",
        message: "Message",
        noMessage: "No message.",
        created: "Created",
        activity: "Activity",
        customerLinked: "Customer record",
        viewCustomer: "View customer",
        convert: "Convert to customer",
        convertHint: "Creates a customer from this lead and marks it Won.",
        converted: "Customer created and lead marked Won",
        convertTitle: "Convert this lead?",
        convertDescription: "A customer record is created from this lead's details, and the lead is marked as Won.",
      },
      stageChangeNote: (from: string, to: string) => `Stage changed from ${from} to ${to}.`,
      createdNote: "Lead added by staff.",
      convertNote: "Converted to a customer.",
    },
    activities: {
      title: "Activity log",
      add: "Add activity",
      type: "Type",
      body: "What happened",
      bodyPlaceholder: "Write a note or summarize the call",
      submit: "Add to log",
      submitting: "Adding",
      empty: "No activity yet.",
      system: "Website",
      by: "by",
      added: "Activity added",
      errorRequired: "Please write something.",
      related: { lead: "Lead", customer: "Customer" },
    },
  },
} as const;

export type Content = typeof content;
