/**
 * ALL user-facing copy lives here. Components import `content` instead of
 * hardcoding text, so wording can be changed (or translated later) in one place.
 * As pages are added, add their sections below.
 */
/** The terms checkbox is a sentence with a link in it, so the sentence is kept in two parts. */
const TERMS_LEAD = "I agree to the ";
const TERMS_LINK = "rental terms and conditions";

export const content = {
  site: {
    name: "Ela's Car Rental",
    tagline: "Simple car rentals across the Philippines",
    description: "Rent a car in the Philippines with simple online booking and clear daily rates in PHP.",
    contactPhone: "0954 326 7335",
    contactEmail: "hello@example.com",
  },

  seo: {
    titleTemplate: "%s | Ela's Car Rental",
    defaultTitle: "Ela's Car Rental | Rent a car in the Philippines",
    locale: "en_PH",
  },

  nav: {
    public: [
      { label: "Home", href: "/" },
      { label: "Vehicles", href: "/vehicles" },
      { label: "Special Offers", href: "/special-offers" },
      { label: "About", href: "/about" },
      { label: "Contact", href: "/contact" },
    ],
    bookCta: { label: "Book now", href: "/book/dates" },
    account: {
      login: "Log in",
      signup: "Sign up",
      hello: (name: string) => `Hi, ${name}`,
      logout: "Log out",
      label: "Your account",
    },
    primaryLabel: "Main navigation",
    skipToContent: "Skip to main content",
  },

  socials: [
    { label: "Facebook", href: "https://facebook.com" },
    { label: "TikTok", href: "https://tiktok.com" },
  ],

  footer: {
    columns: [
      {
        title: "Explore",
        links: [
          { label: "Vehicles", href: "/vehicles" },
          { label: "Special offers", href: "/special-offers" },
          { label: "Book now", href: "/book/dates" },
          { label: "About us", href: "/about" },
        ],
      },
      {
        title: "Support",
        links: [
          { label: "Contact us", href: "/contact" },
          { label: "Leave a review", href: "/review" },
          { label: "Privacy Policy", href: "/privacy" },
          { label: "Rental terms", href: "/terms" },
        ],
      },
    ],
    phoneLabel: "Call us",
    staffLogin: { label: "Staff login", href: "/admin/login" },
    socialsTitle: "Follow us",
    legal: "© 2026 Ela's Car Rental. All rights reserved.",
    credit: "Powered by VAIANI",
  },

  /** Built-in labels used inside UI kit components (mostly accessibility text). */
  ui: {
    loading: "Loading…",
    close: "Close",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    previousMonth: "Go to previous month",
    nextMonth: "Go to next month",
    selectDate: "Select date",
    selectTime: "Select time",
    dismiss: "Dismiss",
    required: "required",
    opensInNewTab: "opens in a new tab",
    notifications: "Notifications",
    pagination: {
      label: "Pagination",
      previous: "Previous",
      next: "Next",
      page: "Page",
    },
    stepper: { label: "Progress", step: "Step", of: "of", complete: "completed" },
    theme: { toggleToLight: "Switch to light mode", toggleToDark: "Switch to dark mode" },
    sort: { ascending: "sorted ascending", descending: "sorted descending" },
    rating: { stars: (n: number) => `${n} out of 5 stars`, option: (n: number) => `${n} ${n === 1 ? "star" : "stars"}` },
    alert: {
      info: "Note",
      success: "Success",
      warning: "Warning",
      danger: "Error",
    },
  },

  /** The loading screen shown on every refresh and while moving between pages. */
  loadingScreen: {
    label: "Loading",
  },

  /** Wording for the reusable empty / error / loading states. */
  states: {
    emptyTitle: "Nothing here yet",
    emptyDescription: "There is nothing to show right now.",
    errorTitle: "Something went wrong",
    errorDescription: "We could not load this. Please try again.",
    retry: "Try again",
    notFoundTitle: "Page not found",
    notFoundDescription: "The page you are looking for does not exist or has moved.",
    backHome: "Back to home",
  },

  /** Form error messages. Used by every Zod schema. */
  validation: {
    required: "This field is required.",
    email: "Enter a valid email address.",
    phone: "Enter a valid mobile number, e.g. 0917 123 4567.",
    messageTooShort: "Please write at least 10 characters.",
    dateInPast: "Choose today or a future date.",
    returnBeforePickup: "Return must be after pick-up.",
    consent: "Please tick this box to continue.",
    passwordShort: "Use at least 8 characters.",
    code: "Enter the 6-digit code.",
    rating: "Choose a star rating from 1 to 5.",
    license: "Enter your driver's license number.",
  },

  /** The words shown for each id in /src/lib/constants.ts. */
  enums: {
    vehicleCategory: {
      suv: "SUV",
      mpv: "Multi-purpose vehicle (MPV)",
      sedan: "Sedan",
      hatchback: "Hatchback",
      van: "Van",
      pickup: "Pick-up truck",
      "125cc": "125cc",
      "150cc": "150cc",
    },
    vehicleStatus: { available: "Available", maintenance: "In maintenance", inactive: "Inactive" },
    leadStage: { new: "New", contacted: "Contacted", qualified: "Qualified", won: "Won", lost: "Lost" },
    leadSource: {
      website: "Website",
      phone: "Phone",
      walk_in: "Walk-in",
      facebook: "Facebook",
      referral: "Referral",
    },
    activityType: { note: "Note", call: "Call", status_change: "Status change" },
    bookingStatus: {
      pending: "Pending",
      confirmed: "Confirmed",
      active: "Active",
      completed: "Completed",
      cancelled: "Cancelled",
    },
    paymentMethod: {
      card: "Credit or debit card",
      gcash: "GCash",
      maya: "Maya",
      paypal: "PayPal",
      wise: "Wise",
      pay_at_pickup: "Pay at pick-up",
    },
    paymentStatus: { pending: "Pending", processing: "Processing", paid: "Paid", failed: "Failed" },
  },

  quickSearch: {
    title: "Find your car",
    pickupLocation: "Pick-up location",
    locationPlaceholder: "Paste a Google Maps link, or type an address",
    locationHint: "For example a hotel, airport terminal or barangay.",
    pickupDate: "Pick-up date",
    pickupTime: "Pick-up time",
    returnDate: "Return date",
    returnTime: "Return time",
    submit: "Search vehicles",
  },

  home: {
    meta: {
      description: "Browse our cars, pick your dates and book online in minutes. Prices in PHP.",
    },
    hero: {
      title: "Rent a car in the Philippines",
      /** Two sentences: the price promise leads (set in full text color), how you book follows. */
      subtitle: { lead: "Clear daily prices in pesos.", rest: "Booked online in minutes." },
    },
    featured: {
      title: "Featured vehicles",
      description: "A few of our most popular cars.",
      viewAll: "View all vehicles",
    },
    howItWorks: {
      title: "How it works",
      steps: [
        { title: "Choose dates and place", body: "Tell us when and where you need the car." },
        { title: "Pick your vehicle", body: "Compare the cars available for your dates." },
        { title: "Book and pay", body: "Confirm your details and pay online or at pick-up." },
        { title: "Pick up and go", body: "Show your booking reference and drive away." },
      ],
    },
    reviews: {
      title: "What customers say",
      description: "Reviews from people who have rented with us.",
      /** The small renter photo carousel under the shorter reviews. Photo files and alt text: assets/config.ts. */
      photos: {
        label: "Photos of our renters",
        caption: "Real renters, with one of our vans",
        previous: "Previous photo",
        next: "Next photo",
        slide: (n: number, total: number) => `${n} of ${total}`,
        counter: (n: number, total: number) => `${n} / ${total}`,
      },
      emptyTitle: "No reviews to show yet",
      emptyDescription: "Be the first to tell us how we did.",
      errorTitle: "We could not load the reviews",
      write: "Write a review",
    },
    /** Closes the home page under the reviews; the button reuses nav.bookCta. */
    cta: { title: "Ready to book your car?" },
  },

  reviews: {
    meta: {
      title: "Leave a review",
      description: "Tell us how we did. Your review goes to our team first.",
    },
    title: "Leave a review",
    subtitle: "Tell us about your experience with our service overall.",
    form: {
      title: "Your review",
      name: "Your name",
      rating: "Your rating",
      comment: "Your comments",
      commentHint: "A few sentences is plenty.",
      reference: "Booking reference",
      referenceHint: "The code from your booking confirmation, like RC-K7M2QA.",
      unknownReference: "We could not find a booking with that reference. Check it and try again.",
      privacyNote: "Reviews are private. Our team reads each one and chooses which to show on the website.",
      submit: "Send review",
      sending: "Sending",
      successTitle: "Thank you for your review",
      successBody: "We received it. Our team will read it and may show it on the website.",
      another: "Write another review",
      errorTitle: "We could not send your review",
      errorBody: "Something went wrong on our side. Please try again.",
    },
  },

  account: {
    login: {
      meta: { title: "Log in", description: "Log in to fill in your booking details faster." },
      title: "Log in",
      subtitle: "Log in to fill in your details for you next time you book.",
      google: "Continue with Google",
      apple: "Continue with Apple",
      or: "or",
      methodsLabel: "How do you want to log in?",
      tabPassword: "Email and password",
      tabCode: "Email code",
      email: "Email",
      password: "Password",
      submit: "Log in",
      submitting: "Logging in",
      sendCode: "Send me a code",
      sendingCode: "Sending",
      codeSent: (email: string) => `We sent a 6-digit code to ${email}.`,
      code: "6-digit code",
      codeDemoNote: "Demo only: no email is sent. Any 6 digits work.",
      verify: "Log in",
      changeEmail: "Use a different email",
      noAccountYet: "New here?",
      signupLink: "Create an account",
      errors: {
        invalid_credentials: "Wrong email or password.",
        invalid_code: "That code is not right. Enter the 6 digits from the email.",
        no_account: "We could not find an account with that email. You can create one instead.",
        unknown: "We could not log you in. Please try again.",
      },
      demo: {
        title: "Demo customer",
        description: "Only shown in this demo. This customer has booked before, so the saved-details prompt appears in the booking.",
        email: "maria.santos@example.com",
        password: "demo1234",
        use: "Use this account",
      },
    },
    signup: {
      meta: { title: "Sign up", description: "Create an account to fill in your booking details faster." },
      title: "Create an account",
      subtitle: "Your details are saved after you book, so next time we can fill them in for you.",
      name: "Full name",
      email: "Email",
      password: "Password",
      passwordHint: "At least 8 characters.",
      submit: "Create account",
      submitting: "Creating account",
      haveAccount: "Already have an account?",
      loginLink: "Log in",
      errors: {
        duplicate_email: "An account with that email already exists. Try logging in instead.",
        unknown: "We could not create your account. Please try again.",
      },
    },
  },

  /** Placeholder legal pages. The company must replace all of this with its approved text before going live. */
  legal: {
    notice: "Placeholder: this text must be replaced with the company's approved version before the website goes live.",
    blank: "[to be set by the company]",
    privacyNote: { lead: "Read how we use your information in our", link: "Privacy Policy" },
    privacy: {
      meta: {
        title: "Privacy Policy",
        description: "Placeholder: how we collect, use and keep your personal information.",
      },
      title: "Privacy Policy",
      subtitle: "Placeholder: how we handle your personal information.",
      sections: [
        {
          title: "What personal data we collect",
          body: [
            "Placeholder: we collect your name, email address, phone number, driver's license number, booking details and any review you write.",
          ],
        },
        {
          title: "Why we use it",
          body: ["Placeholder: [reasons to be set by the company]."],
        },
        {
          title: "Who can see it",
          body: ["Placeholder: company staff can see this information."],
        },
        {
          title: "How long we keep it",
          body: ["Placeholder: [retention period to be set by the company]."],
        },
        {
          title: "Saved details and cookies",
          body: [
            "Placeholder: if you have an account, your name, email, phone number and driver's license number are saved to it so we can offer to fill them in on future bookings. They are only filled in if you choose yes.",
            "Placeholder: they are kept until you ask us to delete them.",
            "Placeholder: a login cookie is used only to keep you signed in.",
          ],
        },
        {
          title: "Payment providers and emails",
          body: [
            "Placeholder: payments may be handled by PayPal, Wise, GCash or Maya, and their own privacy policies apply.",
            "Placeholder: we send emails such as booking confirmations and login codes.",
          ],
        },
        {
          title: "Your rights and how to ask",
          body: ["Placeholder: [your rights to be set out by the company]. To ask, contact us using the details below."],
        },
        {
          title: "Privacy contact",
          body: ["Name: [name]", "Email: [email]"],
        },
      ],
    },
    terms: {
      meta: {
        title: "Rental Terms and Conditions",
        description: "Placeholder: the terms that apply when you rent a vehicle from us.",
      },
      title: "Rental Terms and Conditions",
      subtitle: "Placeholder: the terms that apply to every rental.",
      sections: [
        {
          title: "Who may rent",
          body: ["Placeholder: [driver's minimum age and license requirements to be set by the company]."],
        },
        {
          title: "Booking and payment",
          body: ["Placeholder: [how booking and payment work, to be set by the company]."],
        },
        {
          title: "Rates and rental days",
          body: ["Placeholder: rates are per day. A rental day is 24 hours, so 25 hours counts as 2 days."],
        },
        {
          title: "Deposit",
          body: ["Placeholder: [deposit to be set by the company]."],
        },
        {
          title: "Fuel and mileage",
          body: ["Placeholder: [fuel and mileage rules to be set by the company]."],
        },
        {
          title: "Damage, accidents and insurance",
          body: ["Placeholder: [damage, accident and insurance terms to be set by the company]."],
        },
        {
          title: "Late returns",
          body: ["Placeholder: [late return terms to be set by the company]."],
        },
        {
          title: "Cancellations and changes",
          body: ["Placeholder: [cancellation and change terms to be set by the company]."],
        },
        {
          title: "With a driver, tours and point-to-point trips",
          body: ["Placeholder: [terms for these services to be set by the company]."],
        },
        {
          title: "Contact",
          body: ["Placeholder: [contact details to be set by the company]."],
        },
      ],
    },
  },

  about: {
    meta: {
      title: "About us",
      description: "Learn about our company, our values and our team.",
    },
    title: "About us",
    story: {
      title: "Our story",
      body: [
        "From a car key proposal to building a business and a life together.",
        "We're Peter and Erika. We met in January 2026 and started ELA's Car Rental a month later, in February 2026.",
        "While we were dating, Peter proposed to Erika with something unexpected: a car key and a brand-new car instead of a traditional ring. It stood for the life and the business we were building together.",
        "Today we're husband and wife, and we've both left our jobs to focus fully on ELA's. What started with one car is now a fleet of cars and motorcycles, backed by partners and suppliers we trust.",
        "We want to give locals and tourists across Region VI (Western Visayas) quality vehicles and reliable transportation: self-drive rentals, tours and point-to-point services.",
        "ELA's is now one of the top-rated and fastest-growing local car rental companies in Iloilo, growing alongside established companies with years of industry experience, including brands with an international presence.",
        "We keep our fleet well maintained and our prices clear, so there are no surprises when you book. Many customers come back because the process is simple and the service is dependable.",
      ],
    },
    values: {
      title: "What we stand for",
      items: [
        { title: "Reliable vehicles", body: "Every vehicle is checked and serviced regularly, so it's ready when you are." },
        { title: "Clear pricing", body: "Daily rates in PHP, shown upfront with no hidden fees." },
        { title: "Friendly service", body: "Our team is on hand to help with your booking and answer any questions along the way." },
      ],
    },
    team: {
      title: "Meet the team",
      members: [
        { name: "Peter Agraviador", role: "Owner" },
        { name: "Erika Lasac", role: "Co-owner" },
        { name: "Cynde Agraviador", role: "Admin" },
      ],
    },
    cta: { title: "Questions before you book?", button: "Contact us" },
  },

  specialOffers: {
    meta: {
      title: "Special offers",
      description: "Weekly and monthly rates, a driver, tours and point-to-point trips.",
    },
    title: "Special offers",
    subtitle: "Ways to save, or to get more out of your rental.",
    offers: [
      {
        title: "Weekly and monthly rates",
        body: "Book by the week or the month for a lower daily rate than a short rental.",
      },
      {
        title: "With a driver",
        body: "Add a licensed driver to your booking for an extra charge, and let us do the driving.",
      },
      {
        title: "Tours package",
        body: "A vehicle, a driver and a planned route for day trips and sightseeing.",
      },
      {
        title: "Point-to-point pick-up and drop-off",
        body: "Start in one city or province and end in another, instead of returning to where you started.",
      },
    ],
    cta: { title: "Ask about any of these", button: "Contact us" },
  },

  vehicles: {
    meta: {
      title: "Our vehicles",
      description:
        "Compare SUVs, MPVs, sedans, hatchbacks, vans, pick-up trucks and motorcycles with clear daily rates in PHP.",
    },
    title: "Our vehicles",
    description: "Filter by type, price and seats. Share the page to share your search.",
    filtersTitle: "Filters",
    showFilters: "Show filters",
    hideFilters: "Hide filters",
    filters: {
      category: "Category",
      minSeats: "Seats",
      minPrice: "Min price per day",
      maxPrice: "Max price per day",
      any: "Any",
      noMinimum: "No minimum",
      noMaximum: "No maximum",
      seatsOrMore: (n: number) => `${n}+ seats`,
    },
    sortLabel: "Sort by",
    sorts: {
      "price-asc": "Price: low to high",
      "price-desc": "Price: high to low",
      "name-asc": "Name: A to Z",
      "seats-desc": "Seats: most first",
    },
    resultCount: (n: number) => `${n} ${n === 1 ? "vehicle" : "vehicles"} found`,
    clearFilters: "Clear filters",
    emptyTitle: "No vehicles match your filters",
    emptyDescription: "Try removing a filter or choosing a different price range.",
    trip: {
      title: "Your trip",
      pickup: "Pick-up",
      return: "Return",
      change: "Change search",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
    },
    resultsLabel: "Vehicle results",
  },

  vehicleCard: {
    perDay: "per day",
    totalFor: (days: number) => `Total for ${days} ${days === 1 ? "day" : "days"}`,
    viewDetails: "View details",
    bookNow: "Book now",
    seats: (n: number) => `Up to ${n} seats`,
    unavailable: "Unavailable",
  },

  vehicleDetail: {
    back: "All vehicles",
    /** Under a licensed photo: "Photo: Ethan Llamas, CC BY-SA 4.0 (edited)". */
    photoCredit: (author: string, license: string) => `Photo: ${author}, ${license} (edited)`,
    perDay: "per day",
    specsTitle: "Specifications",
    specs: {
      example: "Example",
      category: "Type",
      seats: "Seats",
    },
    upTo: (n: number) => `Up to ${n}`,
    availabilityTitle: "Availability",
    availableNow: "Available to book",
    unavailableNow: "Not available right now",
    bookNow: "Book now",
    askAbout: "Ask about this vehicle",
    galleryLabel: "Vehicle photos",
    viewPhoto: (n: number) => `View photo ${n}`,
    metaFallbackTitle: "Vehicle",
    metaDescription: (name: string, rate: string) =>
      `Rent the ${name} for ${rate} per day. Book online with clear pricing.`,
  },

  booking: {
    meta: {
      title: "Book your car",
      description: "Book your rental car online in a few simple steps.",
    },
    steps: {
      dates: "Dates and location",
      vehicle: "Vehicle",
      details: "Your details",
      payment: "Payment",
      check: "Check",
      confirmation: "Confirmation",
    },
    common: {
      continue: "Continue",
      back: "Back",
      edit: "Edit",
      loading: "Loading your booking…",
      startOver: "Start over",
    },
    dates: {
      title: "Choose your dates and location",
      description: "Tell us where and when you need the car.",
      pickupLocation: "Pick-up location",
      locationPlaceholder: "Paste a Google Maps link, or type an address",
      locationHint: "For example a hotel, airport terminal or barangay.",
      differentReturn: "Return to a different location",
      returnLocation: "Return location",
      pickupDate: "Pick-up date",
      pickupTime: "Pick-up time",
      returnDate: "Return date",
      returnTime: "Return time",
    },
    vehicle: {
      title: "Choose your vehicle",
      description: "Booking is open: choose any vehicle. Prices shown are per day for your dates.",
      select: "Select",
      selected: "Selected",
      notAvailable: "Not available right now",
      selectPrompt: "Select a vehicle to continue.",
      selectedUnavailable: "Your selected vehicle is not available right now. Please choose another one.",
      loadError: "We could not load the vehicles.",
      vehiclesLabel: "Available vehicles",
    },
    details: {
      title: "Your details",
      description: "We use these to prepare your rental.",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      license: "Driver's license number",
      licenseHint: "The main driver needs a valid license at pick-up.",
      savedDetails: {
        title: "Use your saved details?",
        description: "We can fill in your name, email, phone and license number from your account. You can still change them.",
        yes: "Yes, fill them in",
        no: "No, I will type them",
      },
      loginPrompt: {
        text: "Have an account? Log in to fill in your details for you.",
        link: "Log in",
      },
      notes: "Special requests (optional)",
    },
    payment: {
      title: "Payment",
      description: "Choose how you would like to pay. This is a demo, so no real payment is taken.",
      methodLabel: "Payment method",
      methods: {
        card: { label: "Credit or debit card", description: "Pay with your card." },
        gcash: { label: "GCash", description: "Pay with your GCash wallet." },
        maya: { label: "Maya", description: "Pay with your Maya wallet." },
        paypal: { label: "PayPal", description: "Pay with your PayPal account." },
        wise: { label: "Wise", description: "Pay with your Wise account." },
        pay_at_pickup: {
          label: "Pay at pick-up",
          description: "Pay when you collect the vehicle.",
        },
      },
      cardNotice:
        "Card details are entered on the payment provider's secure page, never on this website. In this demo no card details are asked for.",
      redirectNotice: (method: string) =>
        `You would be sent to ${method} to approve the payment. In this demo, this step is simulated.`,
      pickupNotice:
        "You pay when you collect the vehicle. Your booking stays pending until our team confirms it.",
      pay: (amount: string) => `Pay ${amount} and confirm booking`,
      confirmPickup: "Confirm booking",
      termsLead: TERMS_LEAD,
      termsLink: TERMS_LINK,
      terms: TERMS_LEAD + TERMS_LINK,
      termsError: "Please accept the terms to continue.",
      processing: "Processing your payment. Please do not close this page.",
      failedTitle: "Payment failed",
      failureReasons: {
        declined: "The payment was declined.",
        cancelled: "The payment was cancelled.",
        insufficient_funds: "There were not enough funds.",
      },
      errors: {
        price_changed: {
          title: "The price has changed",
          body: "The daily rate changed while you were checking out. You have not been charged. Please check the new total.",
          action: "Check your booking",
        },
        not_found: {
          title: "We could not find that vehicle",
          body: "Please choose a vehicle again.",
          action: "Choose a vehicle",
        },
        unknown: {
          title: "We could not confirm your booking",
          body: "Something went wrong. Please try again.",
          action: "",
        },
      },
      tryAgain: "Try again",
      demo: {
        title: "Demo controls",
        description: "Only shown in this demo. Choose what the mock payment does.",
        success: "The payment succeeds",
        decline: "The payment is declined",
      },
    },
    check: {
      title: "Check your booking",
      description: "Check everything below. You will pay and confirm on the next step.",
      toPayment: "Continue to payment",
    },
    summary: {
      title: "Booking summary",
      vehicle: "Vehicle",
      noVehicle: "No vehicle selected yet",
      pickup: "Pick-up",
      return: "Return",
      duration: "Duration",
      days: (n: number) => `${n} ${n === 1 ? "day" : "days"}`,
      rate: (rate: string, days: number) => `${rate} × ${days} ${days === 1 ? "day" : "days"}`,
      vehicleLine: "Vehicle rental",
      total: "Total",
      driver: "Driver",
      payment: "Payment",
      pricesNote: "All prices are in PHP and include VAT.",
    },
    confirmation: {
      titleConfirmed: "Booking confirmed",
      titlePending: "Booking received",
      subtitleConfirmed: "Thank you. Your payment was received and your booking is confirmed.",
      subtitlePending: "Thank you. Our team will confirm your booking shortly. You pay at pick-up.",
      reference: "Booking reference",
      referenceHint: "Keep this number. You will need it at pick-up.",
      statusLabel: "Status",
      nextTitle: "What happens next",
      nextSteps: [
        "We email you a confirmation with all the details.",
        "Bring your driver's license and this reference to the pick-up point.",
        "Return the vehicle at the agreed time and place.",
      ],
      toHome: "Back to home",
      browse: "Browse more vehicles",
      notFoundTitle: "Booking not found",
      notFoundDescription: "We could not find a booking with that reference.",
    },
  },

  contact: {
    meta: {
      title: "Contact us",
      description: "Call, email or send us a message and we will get back to you.",
    },
    title: "Contact us",
    subtitle: "Questions about a rental? Send us a message.",
    details: {
      title: "Get in touch",
      phone: "Phone",
      email: "Email",
      address: "Address",
      hours: "Opening hours",
      addressValue: "Unit 000, Placeholder Building, Makati City, Metro Manila",
      hoursValue: "Daily, 7:00 AM to 9:00 PM",
    },
    form: {
      title: "Send us a message",
      name: "Full name",
      email: "Email",
      phone: "Mobile number",
      phoneHint: "For example 0917 123 4567 or +63 917 123 4567",
      vehicle: "Vehicle you are interested in (optional)",
      vehicleNone: "No preference",
      vehiclesLoading: "Loading vehicles…",
      message: "Message",
      consent: "I agree to be contacted about my inquiry",
      submit: "Send message",
      sending: "Sending",
      successTitle: "Message sent",
      successBody: "Thank you. We will get back to you soon.",
      sendAnother: "Send another message",
      errorTitle: "We could not send your message",
      errorBody: "Please check your details and try again.",
    },
  },
  admin: {
    meta: { titleTemplate: "%s | Admin" },
    nav: {
      label: "Admin navigation",
      dashboard: "Dashboard",
      customers: "Customers",
      leads: "Leads",
      pipeline: "Pipeline",
      tasks: "Tasks",
      bookings: "Bookings",
      reports: "Reports",
      pricing: "Pricing",
      reviews: "Reviews",
      users: "Users",
      viewSite: "View website",
    },
    frame: {
      brand: "Admin",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      signedInAs: "Signed in as",
      logout: "Log out",
      loggingOut: "Logging out",
      loading: "Loading your account…",
    },
    login: {
      title: "Staff login",
      description: "Sign in to manage customers, leads and bookings.",
      email: "Email",
      password: "Password",
      submit: "Sign in",
      submitting: "Signing in",
      backToSite: "Back to the website",
      errors: {
        invalid_credentials: "Wrong email or password.",
        account_inactive: "This account is deactivated. Ask an admin to turn it back on.",
        unknown: "We could not sign you in. Please try again.",
      },
      demo: {
        title: "Demo accounts",
        description: "Only shown in this demo. Every account is an admin and uses the same password:",
        use: "Use this account",
        accounts: [{ name: "Ramon Villareal", email: "admin@carrental.example" }],
      },
    },
    common: {
      search: "Search",
      actions: "Actions",
      edit: "Edit",
      delete: "Delete",
      cancel: "Cancel",
      save: "Save",
      saving: "Saving",
      add: "Add",
      back: "Back",
      created: "Created",
      updated: "Updated",
      none: "None",
      unassigned: "Unassigned",
      any: "Any",
      noResultsTitle: "No results",
      noResultsDescription: "Try a different search or remove a filter.",
      clearFilters: "Clear filters",
      showingRange: (from: number, to: number, total: number) => `Showing ${from} to ${to} of ${total}`,
      loadError: "We could not load this.",
      notFoundTitle: "Not found",
      notFoundDescription: "This record does not exist or was deleted.",
      confirmDelete: "Delete",
      saveError: "We could not save your changes. Please try again.",
      saved: "Changes saved",
    },
    dashboard: {
      title: "Dashboard",
      welcome: (name: string) => `Welcome back, ${name}.`,
      cards: {
        leads: "Open leads",
        newLeads: "New leads",
        customers: "Customers",
        activeBookings: "Active bookings",
        pendingBookings: "Pending bookings",
        tasks: "Open tasks",
      },
      cardHints: {
        tasks: (overdue: number) => (overdue === 0 ? "None overdue" : `${overdue} overdue`),
        leads: "Not yet won or lost",
        newLeads: "Waiting for a first contact",
        customers: "In your database",
        activeBookings: "Cars out right now",
        pendingBookings: "Waiting for confirmation",
      },
      leadsByStage: "Leads by stage",
      recentActivity: "Recent activity",
      noActivityTitle: "No activity yet",
      noActivityDescription: "Notes, calls and status changes will appear here.",
      cardsLabel: "Summary",
    },
    customers: {
      title: "Customers",
      description: "Everyone who has booked or was added by your team.",
      searchLabel: "Search customers",
      searchPlaceholder: "Search by name, phone or email",
      columns: { name: "Name", phone: "Phone", email: "Email", bookings: "Bookings", added: "Added" },
      add: "Add customer",
      emptyTitle: "No customers yet",
      emptyDescription: "Customers appear here when they book, or when you add them.",
      form: {
        addTitle: "Add customer",
        editTitle: "Edit customer",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        phoneHint: "For example 0917 123 4567",
        license: "Driver's license number (optional)",
        notes: "Notes",
        duplicateEmail: "A customer with this email already exists.",
      },
      saved: "Customer saved",
      added: "Customer added",
      deleted: "Customer deleted",
      deleteTitle: "Delete this customer?",
      deleteDescription: "This removes the customer and their activity log. It cannot be undone.",
      deleteBlocked: "This customer has bookings, so they cannot be deleted.",
      profile: {
        back: "All customers",
        tabs: { details: "Details", bookings: "Booking history", activity: "Activity" },
        details: "Details",
        contactPerson: "Contact",
        license: "Driver's license",
        notes: "Notes",
        noNotes: "No notes yet.",
        bookings: "Booking history",
        noBookings: "No bookings yet.",
        bookingColumns: { reference: "Reference", vehicle: "Vehicle", dates: "Dates", total: "Total", status: "Status" },
        activity: "Activity",
        customerSince: "Customer since",
      },
    },
    contacts: {
      title: "More contact details",
      description: "Extra phone numbers and emails for this person.",
      add: "Add contact detail",
      empty: "No extra contact details yet.",
      type: "Type",
      label: "Label",
      labelPlaceholder: "e.g. Office, Assistant",
      value: "Phone number or email",
      addTitle: "Add contact detail",
      editTitle: "Edit contact detail",
      deleteTitle: "Delete this contact detail?",
      types: { phone: "Phone", email: "Email" },
      invalidPhone: "Enter a valid phone number.",
      invalidEmail: "Enter a valid email address.",
    },
    leads: {
      title: "Leads",
      description: "People who have asked about a rental. Move them from New to Won or Lost.",
      searchLabel: "Search leads",
      searchPlaceholder: "Search by name, phone or email",
      filters: { stage: "Stage", source: "Source", assignee: "Assigned to" },
      columns: { name: "Name", contact: "Contact", source: "Source", stage: "Stage", vehicle: "Vehicle", assignee: "Assigned to", created: "Created" },
      add: "Add lead",
      emptyTitle: "No leads yet",
      emptyDescription: "Leads from the website contact form and the ones you add show up here.",
      form: {
        addTitle: "Add lead",
        editTitle: "Edit lead",
        name: "Full name",
        email: "Email",
        phone: "Mobile number",
        source: "Source",
        stage: "Stage",
        vehicle: "Vehicle they are interested in",
        noVehicle: "No preference",
        assignee: "Assigned to",
        message: "What they asked for",
      },
      saved: "Lead saved",
      added: "Lead added",
      deleted: "Lead deleted",
      deleteTitle: "Delete this lead?",
      deleteDescription: "This removes the lead and its activity log. It cannot be undone.",
      detail: {
        back: "All leads",
        details: "Details",
        stage: "Stage",
        changeStage: "Change stage",
        stageChanged: "Stage updated",
        assignee: "Assigned to",
        source: "Source",
        vehicle: "Vehicle interest",
        message: "Message",
        noMessage: "No message.",
        created: "Created",
        activity: "Activity",
        customerLinked: "Customer record",
        viewCustomer: "View customer",
        convert: "Convert to customer",
        convertHint: "Creates a customer from this lead and marks it Won.",
        converted: "Customer created and lead marked Won",
        convertTitle: "Convert this lead?",
        convertDescription: "A customer record is created from this lead's details, and the lead is marked as Won.",
      },
      stageChangeNote: (from: string, to: string) => `Stage changed from ${from} to ${to}.`,
      createdNote: "Lead added by staff.",
      convertNote: "Converted to a customer.",
    },
    bookings: {
      title: "Bookings",
      description: "Every rental, from a new booking to a returned car.",
      searchLabel: "Search bookings",
      searchPlaceholder: "Search by reference, customer or vehicle",
      filters: { status: "Status" },
      columns: {
        reference: "Reference",
        customer: "Customer",
        vehicle: "Vehicle",
        pickup: "Pick-up",
        return: "Return",
        total: "Total",
        status: "Status",
        payment: "Payment",
      },
      emptyTitle: "No bookings yet",
      emptyDescription: "Bookings made on the website appear here.",
      detail: {
        back: "All bookings",
        booked: "Booked on",
        trip: "Trip",
        customer: "Customer",
        viewCustomer: "View customer",
        payment: "Payment",
        method: "Method",
        amount: "Amount",
        status: "Status",
        providerRef: "Provider reference",
        notes: "Customer notes",
        noNotes: "No notes.",
        markPaid: "Mark payment as received",
        paymentReceived: "Payment marked as received",
        statusChanged: "Booking status updated",
        priceNote: "These are the prices this booking was made at.",
        nextStep: "Next step",
        finalStatus: "This booking is final. Its status cannot change.",
        actions: {
          confirmed: "Confirm booking",
          active: "Start rental (car picked up)",
          completed: "Complete rental (car returned)",
          cancelled: "Cancel booking",
        },
        cancelTitle: "Cancel this booking?",
        cancelDescription: "The vehicle becomes available again for these dates. This cannot be undone.",
        cancelConfirm: "Cancel booking",
        keep: "Keep booking",
        invalidMove: "That status change is not allowed.",
      },
      statusChangeNote: (reference: string, from: string, to: string) =>
        `Booking ${reference} changed from ${from} to ${to}.`,
      paymentNote: (reference: string, amount: string, method: string) =>
        `Payment of ${amount} (${method}) for booking ${reference} marked as received.`,
    },
    pricing: {
      title: "Vehicle prices",
      description:
        "Change a vehicle's daily rate. New bookings use the new rate. Existing bookings keep the price they were made at.",
      columns: { vehicle: "Vehicle", category: "Category", rate: "Daily rate", status: "Status", actions: "Actions" },
      change: "Change price",
      modalTitle: (name: string) => `Change price: ${name}`,
      currentRate: (rate: string) => `Current rate: ${rate} per day`,
      rateLabel: "New daily rate (PHP)",
      rateHint: "A whole number of pesos, per day.",
      invalid: "Enter a whole number between 100 and 100,000.",
      noChange: "The new rate is the same as the current one.",
      impact: "Existing bookings keep their price. Only new bookings use the new rate.",
      saved: "Price updated",
      empty: "No vehicles found.",
    },
    reviews: {
      title: "Reviews",
      description: "What customers wrote about our service. Only the reviews switched on here appear on the website.",
      columns: { customer: "Customer", rating: "Rating", comment: "Comment", reference: "Booking", date: "Date", show: "On website" },
      showSwitch: (name: string) => `Show ${name}'s review on the website`,
      shown: "Shown",
      hidden: "Hidden",
      shownToast: "Review is now shown on the website",
      hiddenToast: "Review is now hidden from the website",
      emptyTitle: "No reviews yet",
      emptyDescription: "Reviews from customers will appear here.",
    },
    users: {
      title: "Users",
      description: "Staff accounts. Everyone here is an admin and can do everything.",
      columns: { name: "Name", email: "Email", status: "Status", actions: "Actions" },
      statuses: { active: "Active", inactive: "Inactive" },
      you: "(you)",
      add: "Add user",
      form: {
        addTitle: "Add user",
        editTitle: "Edit user",
        name: "Full name",
        email: "Email",
        active: "This account is active",
        passwordNote: "Demo only: every account signs in with the password demo1234.",
      },
      added: "User added",
      saved: "User saved",
      deactivate: "Deactivate",
      reactivate: "Reactivate",
      deactivated: "User deactivated",
      reactivated: "User reactivated",
      deactivateTitle: (name: string) => `Deactivate ${name}?`,
      deactivateDescription: "They will no longer be able to sign in. Their records stay.",
      emptyTitle: "No users yet",
      errors: {
        duplicate_email: "Another user already has this email.",
        last_admin: "At least one account must stay active.",
        self_deactivate: "You cannot deactivate your own account.",
        unknown: "We could not save your changes. Please try again.",
      },
    },
    reports: {
      title: "Reports",
      description: "A simple look at leads, customers, bookings and revenue.",
      range: {
        title: "Date range",
        from: "From",
        to: "To",
        presets: { last30: "Last 30 days", last6Months: "Last 6 months", thisYear: "This year" },
        presetsLabel: "Quick ranges",
        invalid: "The start date must be on or before the end date.",
      },
      summary: {
        label: "Summary for this period",
        leads: "Leads",
        customers: "New customers",
        bookings: "Bookings",
        revenue: "Revenue",
        leadsHint: "Created in this period",
        customersHint: "Added in this period",
        bookingsHint: "Picked up in this period",
        revenueHint: "Confirmed, active and completed",
      },
      tabs: { chart: "Chart", table: "Table" },
      month: "Month",
      leadsByStage: {
        title: "Leads by status",
        description: "Leads created in this period, by the stage they are in now.",
        chartLabel: "Leads by status",
        stage: "Stage",
        count: "Leads",
      },
      overTime: {
        title: "New leads and customers",
        description: "How many were added each month.",
        chartLabel: "New leads and new customers per month",
        leads: "Leads",
        customers: "Customers",
      },
      revenue: {
        title: "Bookings and revenue",
        description:
          "By pick-up month. Revenue counts confirmed, active and completed bookings. Pending and cancelled ones are left out.",
        chartLabel: "Revenue per month",
        bookings: "Bookings",
        revenue: "Revenue",
        total: "Total",
      },
      scroll: (label: string) => `${label}. Scroll sideways to see all of it.`,
    },
    tasks: {
      title: "Tasks",
      description: "Follow-ups and to-dos for your team.",
      searchLabel: "Search tasks",
      searchPlaceholder: "Search by task, person or assignee",
      filters: { status: "Status", assignee: "Assigned to", mine: "Assigned to me" },
      statuses: { open: "Open", done: "Done", all: "All" },
      columns: { done: "Done", title: "Task", due: "Due", assignee: "Assigned to", linked: "About", actions: "Actions" },
      add: "Add task",
      emptyTitle: "No tasks here",
      emptyDescription: "Add a follow-up so nothing gets forgotten.",
      overdue: "Overdue",
      dueToday: "Due today",
      markDone: (title: string) => `Mark done: ${title}`,
      markOpen: (title: string) => `Mark not done: ${title}`,
      form: {
        addTitle: "Add task",
        editTitle: "Edit task",
        title: "What needs doing?",
        due: "Due date",
        assignee: "Assigned to",
        linkType: "About",
        linkNone: "Nothing in particular",
        linkLead: "A lead",
        linkCustomer: "A customer",
        linkTarget: "Which one?",
        choose: "Choose…",
        notes: "Notes",
        linkRequired: "Choose who this task is about.",
        dueRequired: "Choose a due date.",
      },
      added: "Task added",
      saved: "Task saved",
      deleted: "Task deleted",
      doneToast: "Task marked done",
      reopenedToast: "Task reopened",
      deleteTitle: "Delete this task?",
      deleteDescription: "This cannot be undone.",
      linkedCard: {
        title: "Tasks",
        description: "Follow-ups linked to this record.",
        empty: "No tasks yet.",
        add: "Add task",
        viewAll: "View all tasks",
      },
      completedNote: (title: string) => `Task completed: ${title}`,
    },
    pipeline: {
      title: "Pipeline",
      description: "Move leads from New to Won or Lost. Drag a card by its handle, or use the Move to menu.",
      boardLabel: "Lead pipeline",
      assigneeFilter: "Assigned to",
      columnCount: (n: number) => `${n} ${n === 1 ? "lead" : "leads"}`,
      emptyColumn: "No leads",
      moveTo: "Move to",
      dragHandle: (name: string) => `Drag ${name} to another stage`,
      moved: (name: string, stage: string) => `${name} moved to ${stage}`,
      moveFailed: "The lead could not be moved. Please try again.",
      openLead: "Open lead",
      total: (n: number) => `${n} ${n === 1 ? "lead" : "leads"} in the pipeline`,
    },
    activities: {
      title: "Activity log",
      add: "Add activity",
      type: "Type",
      body: "What happened",
      bodyPlaceholder: "Write a note or summarize the call",
      submit: "Add to log",
      submitting: "Adding",
      empty: "No activity yet.",
      system: "Website",
      by: "by",
      added: "Activity added",
      errorRequired: "Please write something.",
      related: { lead: "Lead", customer: "Customer" },
    },
  },
} as const;

export type Content = typeof content;
